[profile.default]
libs = ["lib"]
out = "out"
solc-version = "0.8.16"
src = "src"
test = "test"

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
